### ISSUE TITLE
コードレビュー laco

### ISSUE THREAD

**Issue by lacolaco** [Atoze/OX_Game#10]
- Board#getDefaultValue()のjavadocがおかしい
- Ui#forSelectBoardIndex 名前がおかしい メソッドは動詞！
- OXGameのループがプレイヤー一巡ごとのwhileとプレイヤーひとりごとのforに入れ子になっているのが少し違和感がある。今のターン数がわかればどちらの手番かはわかるので、whileだけでいいんじゃないかと思う

おおざっぱに良いけど、テストが少ない

**Comment by Atoze** [comment]
- [x] Board#getDefaultValue()のjavadocがおかしい
- [x] Ui#forSelectBoardIndex メソッドは動詞！
- [x] OXGameのループがプレイヤー一巡ごとのwhileとプレイヤーひとりごとのforに入れ子になっているのが少し違和感がある。今のターン数がわかればどちらの手番かはわかるので、whileだけでいいんじゃないかと思う

- [x] テスト少ない
