### ISSUE TITLE
コードレビュー vv 2nd

### ISSUE THREAD

**Issue by vvakame** [Atoze/OX_Game#16]
* `BoardImpl board = new SquaredBoard(gridSize);` は `Board board` であるべき
  * BoardImpl は隠蔽のための苦肉の策的なものなので表側に名前がちょいちょい出てくるのはおかしい
  * というか BoardImpl いらなくて Board に統合でいいのでは？
* フォーマッタかかってない
* OXGame と OXGameJudge が分かれているのも謎っぽい
  * 統合してしまっていいのでは？
* basicとの分割がわりと謎
  * NormalCPU, SquaredBoard がここに属するなら CharacterUI, EasyCPU, HumanPlayer も属するべきなのでは？

総評：表面上のパターンをなぞっていて、具体的な狙いが不明確なのでは？という点が散見される。
全体としては1月前くらいと比べるとだんぜんよくなった。

**Comment by Atoze** [comment]
- [x] BoardImpl board = new SquaredBoard(gridSize); は Board board であるべき
BoardImpl は隠蔽のための苦肉の策的なものなので表側に名前がちょいちょい出てくるのはおかしい

- [x] フォーマッタかかってない

- [x] OXGame と OXGameJudge が分かれているのも謎っぽい
統合してしまっていいのでは？

- [x] basicパッケージとの分割がわりと謎
それぞれの属性ごとにパッケージ分けをした

**Comment by Atoze** [comment]
> というか BoardImpl いらなくて Board に統合でいいのでは？

現状、Player等に渡すBoardも実際の処理を行なってるBoardも同参照であるため、なるべく渡す先にはinsertメソッドを渡したくない次第です。

Boardインスタンスをディープコピーした(clone)ものを渡せばよいのでは？とも思ったのですが、
javaではあまりイケてないらしく、どのように処理すべきなのか迷走中です…

**Comment by Atoze** [comment]
アクセス権の調整で解決
