### ISSUE TITLE
コードレビュー laco

### ISSUE THREAD

**Issue by lacolaco** [Atoze/OX_Game#7]
だいたいよさそう？コードの細かいところは置いておいて設計的な部分をメインに

## Main

```
        OXGame game = new OXGame();
        game.start(board, players, gridNum, ui);
```

これはコンストラクタで渡したあとに `start()` のほうが自然じゃないか？という気がする

## CharacterUI

- `setCharacter` は名前おかしい 
- `System.out.print();` が多いので結構読みにくい　事前に文字列組み立てられないかな、っていう気がする
- メソッド名がちょいちょいおかしい `turnStart`ではなく`startTurn`だろうし、`gameSet`も`printGameResult`とかじゃないかな ResultはGO_ON状態も持っているんだし

## ComputerPlayer

- これが何のために必要かよくわからない。PlayerがHumanかCPUかどうかを区別する必要がでてきたら、それは抽象化に失敗しているのではないだろうか。GameやCUIからはただのPlayerとして扱える状態を維持すべきだと思う

## HumanPlayer

- 入力を促すためにprintlnしているけど、実はこれはCUIに依存しているはず。UIによってどうメッセージを出すかは変わるはずなので、入力を促すメッセージもUI側に表示を委ねないといけない

**Comment by Atoze** [comment]
## Main
- [x] 値をコンストラクタで渡したあとに start() のほうが自然

## CharacterUI
- [x] setCharacterは名前おかしい
- [x] System.out.print();が多いので結構読みにくい　事前に文字列組み立てよう
- [x] メソッド名がおかしい　turnStart→startTurn、gameSet→printGameResultとか

## ComputerPlayer
- [x] コンピューターと人間を区別する必要が出てきたら、抽象化に失敗してるのでいらない

## HumanPlayer
- [x] 入力を促すメッセージもUI側に表示を委ねないといけない
