### ISSUE TITLE
コードレビュー vv

### ISSUE THREAD

**Issue by vvakame** [Atoze/OX_Game#8]
* CharacterUI に X と O が定義してあるの微妙では？
  * `CharacterUI ui = new CharacterUI();` は `UI ui = new CharacterUI();` でもコンパイルが通ったほうがいいと思う
* gridNum は gridSize とかのほうがよさそう
* `game.start(board, players, gridNum, ui);` としているが、gridNumはBoardが持っていて管理しているのであればboardから取ったほうがいいのでは？
* 全体的にもうちょっとJavadoc書いたほうがいいと思った
  * 特にinterface
* HumanPlayer内部でCharacterUI前提のコードが書かれてて若干惜しい
  * でもこの辺整理するのめんどいんだよね(わかる
  * 同じく OXGame に `System.exit(0);` があってこれもCUI前提だ

まだ途中(明日やる

**Comment by vvakame** [comment]
* Match クラスが浮いてる
  * 動詞をクラス名に当てるのは大抵変な事してる
  * OXGame か Board あたりに持たせたほうがいいのでは
* Board と ScreenBoard が謎だ
  * 継承関係にあるのかと思ったら特に無さそう…？
  * ScreenBoard いらないのでは…？
* OXGameTest で勝負が付いてゲームが正常終了できるところまでテストする方法があるだろうか？

**Comment by Atoze** [comment]
## UI
- [x] HumanPlayer内部でCUI前提のコードが書かれてる　※lacoさんのと共通の指摘
- [x] OXGame の System.exit(0); もCUI前提

## CharacterUI
- [x] CharacterUIに X と O が定義してあるの微妙では？→○×指定方法を考える（enum?）

## Board類
- [x] gridNum は gridSizeの方が良さげ

## Match
- [x] OXGame か Board あたりに持たせたほうがいいのでは
長くなってしまうので勝利判定を外に切り出しました

## OXGameTest
- [x] 正常にゲームが終わったかの基準がないためテストになっていない

## 全体的な話
- [x] Javadoc書こう（特にinterface）

**Comment by Atoze** [comment]
> game.start(board, players, gridNum, ui); としているが、gridNumはBoardが持っていて管理しているのであればboardから取ったほうがいいのでは？

`マークが一直線にn個並べば勝ち` というのが勝利条件で、gridNumがそのn個に当たります。
勝利条件を、状態を保持しているBoardから取るのが正しいのだろうか？という疑問があります。

ただ、n個という値が、ボードの形や状態などに起因し、複数のnの状態を持つのであればBoard内のデータからOXGameで調整したほうが良いと思います。（例:4*3という形の場合は、横に4個、縦に3個など）

> Board と ScreenBoard が謎だ
継承関係にあるのかと思ったら特に無さそう…？
ScreenBoard いらないのでは…？

Boardをそのまま渡してしまうと、Boardの状況を対決処理以外で好き勝手弄られてしまう恐れがあるため、状況を見るためだけのクラスを作成しました.
名前的に怪しいのでBoardViewerといたしましたが、いかがでしょうか。

**Comment by vvakame** [comment]
> 好き勝手弄られてしまう恐れがあるため

が謎(ほんとか？と思っている

**Comment by Atoze** [comment]
勝利判定をOXGameに委ねてるので、OXGame内の`this.board`を置き換えられない限り別クラスのに渡されたBoardを弄ってもゲームの進行上妨げになることはなく、わざわざ用意しなくても良いって感じでしょうか…？

**Comment by Atoze** [comment]
悪意のあるプレイヤーを入れないためにも、`List<Player>` をクラスで管理した方がよさげ…？
（そもそも現段階では悪意のあるプレイヤークラスがどう実装出来るかわからないから、対処の仕様がないけど、OXGameが持ってるBoard保持メモリを弄られたらゲームが崩壊する）

**Comment by Atoze** [comment]
## this.board参照問題
- [x] `clone()`所謂ディープコピーの実装上の問題
cloneメソッドをBoardサブクラスに実装すると、cloneメソッドの仕組みがわからないと辛そう
効率よく書くにはサブクラスがBoard以外にClonableを継承している必要があるけどどうなのか

...抽象クラス化？そういう点ではデータの保持の方法が一次配列に限定されてしまうけどそれはそれで問題がありそうなむしろ良さそうな

インスタンスを新規作成して中身を全てコピーしようとすると、immutableなfieldまで新たにメモリ確保して下手すると激重くなるからあまり推奨できない

**Comment by Atoze** [comment]
Board(挿入メソッドなし)-implements→BoardImpl(挿入メソッド付)手法
 ``` 
BoardImpl boardController = new SquaredBoard(int);
Board screenBoard = boardController;

boardController.insert()→○
screenBoard.insert()→×
``` 
//悪意のあるPlayerImpl Class
``` 
BoardImpl playerBoard = (BoardImpl) screenBoard;

screenBoard.insert()→×
playerBoard.insert()→○ アカン
``` 
で操作メソッドに手を伸ばせると考えると、
変数の参照は別々にしておいた方が良い気もするけどどう実装しよう

**Comment by Atoze** [comment]
普通にclone()の方法でもBoardサブクラスが自分のインスタンスをそのまま返すって感じに作成すればいくらでも破壊可能なのでどっちもどっちかもしれない

前者はBoardのclone()の中身を書き換える、(アドレス比較して一致してたら例外を返すことによって予防できそうだけどどこで予防するかとかの問題が)
後者はBoardImplがBoardにcastから作成出来ることを知っていたら破壊可能　って感じ

**Comment by Atoze** [comment]
clone()はあまりイケてはないらしい
